[package]
name = "multipaint"
version = "0.1.0"
authors = ["Martin Broesamle <m@m-broe.de>"]

[dependencies]
piston = "0.24.0"
pistoncore-glutin_window = "0.28.0"
piston2d-opengl_graphics = "0.31.0"
piston2d-graphics = "0.16.0"
